version: '3.9'

services:
  baikal:
    image: ckulka/baikal:0.9.5-nginx
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./config:/var/www/baikal/config
      - ./specific:/var/www/baikal/Specific
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.baikal.rule=Host(`${SERVER_DOMAIN:-example.com}`)"
        - "traefik.http.routers.baikal.entrypoints=websecure"
        - "traefik.http.routers.baikal.tls=true"
        - "traefik.http.routers.baikal.tls.certresolver=acme-resolver"
        - "traefik.http.services.baikal.loadbalancer.server.port=80"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
