version: '3.9'

services:
  syncthing:
    image: syncthing/syncthing:${VERSION_SYNCTHING:-1.29.6}
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./sync-folders:/var/syncthing
    ports:
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      - PUID=1000
      - PGID=1000
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.syncthing.entrypoints=websecure"
        - "traefik.http.routers.syncthing.rule=Host(`${SERVER_DOMAIN:-sync.example.com}`)"
        - "traefik.http.routers.syncthing.tls=true"
        - "traefik.http.routers.syncthing.tls.certresolver=acme-resolver"
        - "traefik.http.services.syncthing.loadbalancer.server.port=8384"
        - "traefik.docker.network=traefik-public"

networks:
  traefik-public:
    external: true
